[package]
name = "ebook_meta_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
cli-log = "2.1.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
epub = "2.1.4"
ratatui = "0.29.0"
tui-widget-list = "0.13.2"
